// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// ใช้ในการ initializeApp ทุกครั้งที่จะต่อ
    // FirebaseApp touristApp = await Firebase.initializeApp(
    //   name: 'touristApp',
    //   options: DefaultFirebaseOptionsTourist.currentPlatform,
    // );
    // FirebaseFirestore touristAppFirestore =
    //     FirebaseFirestore.instanceFor(app: touristApp);


class DefaultFirebaseOptionsTourist {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPF1gal6cQCelQLef3SjJJdrGagOsb2YQ',
    appId: '1:261705225576:android:ec025238b8a9f25498b2dd',
    messagingSenderId: '261705225576',
    projectId: 'ggt-tourist-utccfp',
    storageBucket: 'ggt-tourist-utccfp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHWpfBFXQ3zL7pkVUrj957s5Xvhva0a7c',
    appId: '1:261705225576:ios:dcf053a6e9a65ac998b2dd',
    messagingSenderId: '261705225576',
    projectId: 'ggt-tourist-utccfp',
    storageBucket: 'ggt-tourist-utccfp.appspot.com',
    iosClientId:
        '261705225576-5fthn77f986ic19ddk02rkonvbfjt84f.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggtTouristUtccfinalproject',
  );
}
