// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP_8U67AUjaFPPmk0l1JZLVsAjN8TBQL8',
    appId: '1:301228477141:web:e57d8a644cfee3baa4b05c',
    messagingSenderId: '301228477141',
    projectId: 'ggt-admin-utccfp',
    authDomain: 'ggt-admin-utccfp.firebaseapp.com',
    storageBucket: 'ggt-admin-utccfp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOcw-TzDEvDHzRn83FtXTujltbk1nTMgI',
    appId: '1:301228477141:android:9da5b3907c7d2a5aa4b05c',
    messagingSenderId: '301228477141',
    projectId: 'ggt-admin-utccfp',
    storageBucket: 'ggt-admin-utccfp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXKwwIlLac2efbmuBaoBVn438ecArvD80',
    appId: '1:301228477141:ios:c3434f29dc582382a4b05c',
    messagingSenderId: '301228477141',
    projectId: 'ggt-admin-utccfp',
    storageBucket: 'ggt-admin-utccfp.appspot.com',
    iosClientId: '301228477141-i5bh4rh2t714h94u60lrafejcum2nkq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.ggtAdminUtccfinalproject',
  );
}
